#!/bin/python3
import argparse
from os import path
from logger import log as logger
from waveman import WaveMan


def main():
    parser = argparse.ArgumentParser(
        description="Creates cool-lookin' audio waveform visualisations to use as assets in players and videos.")

    parser.add_argument(
        '--input', help='Input file path. Required', required=True, type=str)
    parser.add_argument(
        '--steps', help='The total number of steps done. [Default 64]', default=64, type=int)
    parser.add_argument(
        '--totalwidth', help='The total width of the image. [Default 2000]', default=2000, type=int)
    parser.add_argument(
        '--stepwidth', help='Width of each step. Can derive the total width by providing --steps and --stepwidth. [Default 45]', default=45, type=float)
    parser.add_argument(
        '--height', help='The total height of the image. [Default 300]', default=300, type=int)
    parser.add_argument(
        '--output', help='Output file path. [Default $input]', type=str)
    parser.add_argument(
        '--color', help="The fill color for the bars. [Default 'black']", default="black", type=str)
    parser.add_argument(
        '--rounded', help="Rounded corner radius. [Default 0]", default=0, type=float)
    parser.add_argument(
        '--mode', help="Sample visualization mode. Either 'avg' or 'max' [Default 'rounded_avg']", default="rounded_avg", type=str, choices=["avg", "max", "rnd_avg"])
    parser.add_argument(
        '--align', help="Vertical bar alignment. Either 'center' or 'bottom' [Default 'center']", default="center", type=str, choices=["bottom", "center"])
    args = parser.parse_args()

    # print(args)

    if args.input:
        filename = args.input
    else:
        logger("Missing input file")
        return

    if args.output:
        output = args.output
    else:
        output = './' + path.basename(filename).replace('.mp3', '')

    if args.steps:
        steps = int(args.steps)
    else:
        steps = 64

    if args.stepwidth:
        step_width = int(args.stepwidth)
    else:
        step_width = 20

    if args.rounded:
        rounded = int(args.rounded)
    else:
        rounded = step_width / 2

    if args.color:
        color = args.color
    else:
        color = "black"

    x_gap = 0.1 * step_width

    if args.height:
        step_height = int(args.height)
    else:
        step_height = 300

    if args.mode:
        if args.mode == "avg" or args.mode == "max" or args.mode == "rounded_avg":
            mode = args.mode
        else:
            logger(
                "Found unsupported transformation mode. Only supports 'avg', 'rounded_avg' and 'max'", mode=args.mode)
            mode = "avg"
    else:
        mode = "rounded_avg"

    if args.align:
        if args.align == "bottom" or args.align == "center":
            align = args.align
        else:
            logger(
                "Found unsupported alignment. Only supports 'center' and 'bottom'", align=args.align)
            align = "center"
    else:
        align = "center"

    config = {
        "align": align,
        "mode": mode,
        "step_width": step_width,
        "height": step_height,
        "rounded": rounded,
        "gap": x_gap,
        "steps": steps,
        "color": color,
        "sr": 48000,
        "scale": 1,
        "mono": True,
        "dpi": 600,
        "preserveAspectRatio": "meet",
    }

    svg = WaveMan(filename, config=config).run().to_string()

    with open(f"{output}.svg", "w") as f:
        f.write(svg)
        f.close()


if __name__ == '__main__':
    main()
